-- MySQL Script generated by MySQL Workbench
-- jeu. 01 août 2019 16:04:39 CEST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Ocpizza
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Ocpizza
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Ocpizza` DEFAULT CHARACTER SET cp1250 ;
SHOW WARNINGS;
USE `Ocpizza` ;

-- -----------------------------------------------------
-- Table `Ocpizza`.`address`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Ocpizza`.`address` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(30) NOT NULL,
  `address` VARCHAR(30) NOT NULL,
  `complement_1` VARCHAR(30) NOT NULL,
  `complement_2` VARCHAR(30) NULL,
  `city` VARCHAR(30) NOT NULL,
  `postal_code` CHAR(5) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `city_code_idx` (`city` ASC, `postal_code` ASC),
  UNIQUE INDEX `postal_code_UNIQUE` (`postal_code` ASC),
  UNIQUE INDEX `city_UNIQUE` (`city` ASC))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Ocpizza`.`phone`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Ocpizza`.`phone` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `number` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Ocpizza`.`client`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Ocpizza`.`client` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(30) NOT NULL,
  `name` VARCHAR(30) NOT NULL,
  `mail` VARCHAR(45) NOT NULL,
  `login` VARCHAR(30) NOT NULL,
  `password` BINARY(32) NOT NULL,
  `delivery_address_id` INT NOT NULL,
  `phone_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_delivry_address_id_idx` (`delivery_address_id` ASC),
  INDEX `fk_phone_id_c_idx` (`phone_id` ASC),
  CONSTRAINT `fk_delivery_address_id_c`
    FOREIGN KEY (`delivery_address_id`)
    REFERENCES `Ocpizza`.`address` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_phone_id_c`
    FOREIGN KEY (`phone_id`)
    REFERENCES `Ocpizza`.`phone` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Ocpizza`.`employee`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Ocpizza`.`employee` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(30) NOT NULL,
  `name` VARCHAR(30) NOT NULL,
  `mail` VARCHAR(45) NOT NULL,
  `login` VARCHAR(30) NOT NULL,
  `password` BINARY(32) NOT NULL,
  `address_id` INT NOT NULL,
  `phone_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_address_id_idx` (`address_id` ASC),
  INDEX `fk_phone_id_idx` (`phone_id` ASC),
  CONSTRAINT `fk_address_id_e`
    FOREIGN KEY (`address_id`)
    REFERENCES `Ocpizza`.`address` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_phone_id_e`
    FOREIGN KEY (`phone_id`)
    REFERENCES `Ocpizza`.`phone` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Ocpizza`.`restaurant`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Ocpizza`.`restaurant` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(25) NOT NULL,
  `address_id` INT NOT NULL,
  `phone_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_phone_id_idx` (`phone_id` ASC),
  INDEX `fk_adresse_id_idx` (`address_id` ASC),
  CONSTRAINT `fk_phone_id_r`
    FOREIGN KEY (`phone_id`)
    REFERENCES `Ocpizza`.`phone` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_adresse_id_r`
    FOREIGN KEY (`address_id`)
    REFERENCES `Ocpizza`.`address` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Ocpizza`.`order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Ocpizza`.`order` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `order_num` VARCHAR(45) NOT NULL,
  `date` DATETIME NOT NULL,
  `status` VARCHAR(10) NOT NULL,
  `employee_id` INT NOT NULL,
  `restaurant_id` INT NOT NULL,
  `client_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_client_id_idx` (`employee_id` ASC),
  INDEX `fk_restaurant_id_idx` (`restaurant_id` ASC),
  INDEX `fk_client_id_idx1` (`client_id` ASC),
  CONSTRAINT `fk_employee_id_o`
    FOREIGN KEY (`employee_id`)
    REFERENCES `Ocpizza`.`employee` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_restaurant_id_o`
    FOREIGN KEY (`restaurant_id`)
    REFERENCES `Ocpizza`.`restaurant` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_client_id_o`
    FOREIGN KEY (`client_id`)
    REFERENCES `Ocpizza`.`client` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Ocpizza`.`pizza`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Ocpizza`.`pizza` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `taxe_price` DECIMAL(6,2) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Ocpizza`.`bill`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Ocpizza`.`bill` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `date` DATETIME NOT NULL,
  `all_taxe_price` DECIMAL(6,2) NOT NULL,
  `payment_type` VARCHAR(30) NOT NULL,
  `order_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_order_id_idx` (`order_id` ASC),
  CONSTRAINT `fk_order_id_b`
    FOREIGN KEY (`order_id`)
    REFERENCES `Ocpizza`.`order` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Ocpizza`.`ingredient`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Ocpizza`.`ingredient` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Ocpizza`.`order_line`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Ocpizza`.`order_line` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `quantity` INT NOT NULL,
  `status` VARCHAR(30) NOT NULL,
  `order_id` INT NOT NULL,
  `pizza_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_order_id_ol` (`order_id` ASC),
  INDEX `fk_pizza_id_idx` (`pizza_id` ASC),
  CONSTRAINT `fk_order_id_ol`
    FOREIGN KEY (`order_id`)
    REFERENCES `Ocpizza`.`order` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pizza_id_ol`
    FOREIGN KEY (`pizza_id`)
    REFERENCES `Ocpizza`.`pizza` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Ocpizza`.`(assoc) composition`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Ocpizza`.`(assoc) composition` (
  `quantity` INT NOT NULL,
  `pizza_id` INT NOT NULL,
  `ingredient_id` INT NOT NULL,
  INDEX `fk_pizza_id_idx` (`pizza_id` ASC),
  INDEX `fk_ingredient_id_idx` (`ingredient_id` ASC),
  PRIMARY KEY (`pizza_id`, `ingredient_id`),
  CONSTRAINT `fk_pizza_id_co`
    FOREIGN KEY (`pizza_id`)
    REFERENCES `Ocpizza`.`pizza` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ingredient_id_co`
    FOREIGN KEY (`ingredient_id`)
    REFERENCES `Ocpizza`.`ingredient` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Ocpizza`.`(assoc) stock`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Ocpizza`.`(assoc) stock` (
  `quantity` INT NOT NULL,
  `ingredient_id` INT NOT NULL,
  `restaurant_id` INT NOT NULL,
  INDEX `fk_ingredient_id_idx` (`ingredient_id` ASC),
  INDEX `fk_restaurant_id_idx` (`restaurant_id` ASC),
  PRIMARY KEY (`ingredient_id`, `restaurant_id`),
  CONSTRAINT `fk_ingredient_id_s`
    FOREIGN KEY (`ingredient_id`)
    REFERENCES `Ocpizza`.`ingredient` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_restaurant_id_s`
    FOREIGN KEY (`restaurant_id`)
    REFERENCES `Ocpizza`.`restaurant` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
